export const ADMIN_STATUS_META = {
  ACTIVE: { label: '활성', tone: { background: '#dcfce7', color: '#166534', border: '#86efac' } },
  INVITED: { label: '초대 대기', tone: { background: '#fef3c7', color: '#92400e', border: '#fcd34d' } },
  INACTIVE: { label: '비활성', tone: { background: '#e5e7eb', color: '#374151', border: '#cbd5e1' } },
  LOCKED: { label: '잠금', tone: { background: '#fee2e2', color: '#991b1b', border: '#fca5a5' } },
};

export const ROLE_META = {
  '슈퍼 관리자': { tone: { background: '#dbeafe', color: '#1d4ed8', border: '#93c5fd' } },
  '운영 관리자': { tone: { background: '#cffafe', color: '#155e75', border: '#67e8f9' } },
  '상담 관리자': { tone: { background: '#ede9fe', color: '#6d28d9', border: '#c4b5fd' } },
  '모니터링 전용': { tone: { background: '#fce7f3', color: '#9d174d', border: '#f9a8d4' } },
};

export const ACCOUNT_ROLE_OPTIONS = [
  '슈퍼 관리자',
  '운영 관리자',
  '상담 관리자',
  '모니터링 전용',
];

export const ADMIN_ACCOUNTS = [
  {
    id: 'adm-001',
    name: '윤혜진',
    email: 'admin@carecall.kr',
    role: '슈퍼 관리자',
    status: 'ACTIVE',
    orgName: '서울북부 돌봄센터',
    department: '운영 총괄',
    title: '센터장',
    phone: '010-7281-1024',
    lastAccess: '2026-04-02T08:55:00+09:00',
    createdAt: '2026-03-10T09:00:00+09:00',
    invitedBy: '시스템 초기 설정',
    location: '서울 본부 / Chrome',
    permissions: ['전체 대상자 보기', '관리자 계정 생성', '권한 변경', '보안 정책 관리'],
    notes: '서비스 론칭 전 전체 운영 정책을 검토하는 초기 관리자',
  },
  {
    id: 'adm-002',
    name: '김도윤',
    email: 'ops@carecall.kr',
    role: '운영 관리자',
    status: 'ACTIVE',
    orgName: '서울북부 돌봄센터',
    department: '운영 지원',
    title: '운영 매니저',
    phone: '010-4422-9191',
    lastAccess: '2026-04-02T07:40:00+09:00',
    createdAt: '2026-03-11T14:30:00+09:00',
    invitedBy: '윤혜진',
    location: '서울 본부 / Edge',
    permissions: ['대상자 보기', '운영 현황 열람', '기본 설정 편집'],
    notes: '일일 운영 현황 확인과 신규 대상자 등록 검토 담당',
  },
  {
    id: 'adm-003',
    name: '박서현',
    email: 'counselor@carecall.kr',
    role: '상담 관리자',
    status: 'INVITED',
    orgName: '서울북부 돌봄센터',
    department: '상담 운영',
    title: '상담 코디네이터',
    phone: '010-9021-8812',
    lastAccess: '초대 메일 발송됨',
    createdAt: '2026-04-01T16:15:00+09:00',
    invitedBy: '윤혜진',
    location: '원격 예정',
    permissions: ['위험군 모니터링', '통화 이력 열람', '알림 확인'],
    notes: '위험군 대응 프로세스 검토를 위한 신규 상담 관리자 초대 상태',
  },
  {
    id: 'adm-004',
    name: '정하늘',
    email: 'viewer@carecall.kr',
    role: '모니터링 전용',
    status: 'LOCKED',
    orgName: '서울북부 돌봄센터',
    department: '품질 모니터링',
    title: 'QA 모니터',
    phone: '010-7334-2201',
    lastAccess: '보안 잠금 처리',
    createdAt: '2026-03-28T10:20:00+09:00',
    invitedBy: '김도윤',
    location: '서울 본부 / Safari',
    permissions: ['현황판 보기', '위험 경보 확인'],
    notes: '반복 로그인 실패 시나리오를 검토하기 위한 잠금 상태 목업',
  },
];

export const SECURITY_EVENTS = [
  {
    id: 'sec-001',
    title: '슈퍼 관리자 로그인',
    description: 'admin@carecall.kr 계정으로 오전 운영 점검을 수행했습니다.',
    severity: 'info',
    location: '서울 본부 / Chrome',
    createdAt: '2026-04-02T08:55:00+09:00',
  },
  {
    id: 'sec-002',
    title: '초대 메일 발송',
    description: '상담 관리자 계정 초대 메일이 발송되었습니다.',
    severity: 'medium',
    location: '서울 본부 / Chrome',
    createdAt: '2026-04-01T16:15:00+09:00',
  },
  {
    id: 'sec-003',
    title: '잠금 알림',
    description: 'viewer@carecall.kr 계정이 반복 인증 실패로 잠금 상태가 되었습니다.',
    severity: 'high',
    location: '원격 접속 / Safari',
    createdAt: '2026-04-01T09:25:00+09:00',
  },
];
